### ISSUE TITLE
24题的答案写成23题的了，我的好像不太行557.66 (97.9% match)

### ISSUE THREAD

**Issue by guahunyo** [chokcoco/css-battle-answer#2]
<p><p i><style>body{background:#62306D}p{top:30;left:80;position:fixed;height:150;width:100;border-radius:59q;color:E38F66;background:#AA445F;box-shadow: 150q 55q}[i]{height:100;width:100;top:77;border-radius:59q;background:#F7EC7D;box-shadow:150q 0 #F7EC7D

**Comment by guahunyo** [comment]
<p><p i><style>body{background:#62306D}p{top:30;left:80;position:fixed;height:150;width:100;border-radius:59q;color:E38F66;background:#AA445F;box-shadow: 150q 55q}[i]{height:100;width:100;top:77;border-radius:59q;background:#F7EC7D;box-shadow:150q 0 #F7EC7D

**Comment by wch243294382** [comment]
为啥这些答案后面都没写完,但放上去能跑呢
