### ISSUE TITLE
Code does not match with the target name

### ISSUE THREAD

**Issue by wblazej** [chokcoco/css-battle-answer#3]
https://github.com/chokcoco/css-battle-answer/blob/master/Switches.md
In this target solution the code doesn't match with target name and picture.

The code is from this target:
https://github.com/chokcoco/css-battle-answer/blob/master/Cloud.md

**Comment by chokcoco** [comment]
> https://github.com/chokcoco/css-battle-answer/blob/master/Switches.md
> In this target solution the code doesn't match with target name and picture.
> 
> The code is from this target:
> https://github.com/chokcoco/css-battle-answer/blob/master/Cloud.md

Thanks, it has been fixed.
